num1 =  10
num2 = 2
plus = num1+num2
minus = num1-num2
multiplied = num1*num2
divide =int(num1/num2)
print(num1,"+",num2, "=", plus)
print(num1,"-",num2, "=", minus)
print(num1,"*",num2, "=", multiplied)
print(num1,"/",num2, "=", divide)
